db:
  username: ${username.value:postgres}
  password: 1234567
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  properties:
    first: 123
    second: 567
    third.value: Third
  pool:
    size: 12
    timeout: 100
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

logging:
  level:
    root: WARN
    com.edu.spring.database.pool.ConnectionPool: INFO
  file:
    name: dmdev.log
    path: /


